version: "3"
services: 
    app: 
        image: cdmoss/elixr
        ports: 
            - "5000:5000"
    proxy: 
        image: nginx:alpine
        depends_on: 
            - app
        ports: 
            - "80:80"
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf:ro