using ElixrMarket.Web.Data;
using ElixrMarket.Web.Models;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ElixrMarket.Web.Services
{
    public interface IProductsService
    {
        Task<Product> GetProductById(int id);
    }

    public class EFCoreProductsService : IProductsService
    {
        private readonly ElixrDataContext _context;
        private List<Product> products = new List<Product> 
        {
                new Product { Id = 1, Name = "Test product 1", Price = 4.99m, Summary = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec sem condimentum odio auctor tristique vestibulum in lacus. Praesent eu ultricies lectus. Integer justo dui, luctus nec porttitor ac, lobortis quis sem. Aliquam erat volutpat. Sed vitae semper enim. Vivamus ut leo quis tortor scelerisque ultricies. Proin aliquet, arcu sit amet rhoncus rhoncus, nisl felis rhoncus sapien, sit amet iaculis velit quam sit amet nisi. ", Description = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec sem condimentum odio auctor tristique vestibulum in lacus. Praesent eu ultricies lectus. Integer justo dui, luctus nec porttitor ac, lobortis quis sem. Aliquam erat volutpat. Sed vitae semper enim. Vivamus ut leo quis tortor scelerisque ultricies. Proin aliquet, arcu sit amet rhoncus rhoncus, nisl felis rhoncus sapien, sit amet iaculis velit quam sit amet nisi.
Aliquam cursus viverra erat, at luctus quam ornare eu. Vestibulum a pretium mi. Sed ultrices, mi in eleifend aliquet, velit tellus feugiat libero, eu tincidunt diam sapien ac sapien. In rutrum lacus quis mi cursus, non sollicitudin ligula porttitor. Curabitur sem leo, laoreet at sollicitudin eu, dapibus eu enim. Nullam libero mi, sollicitudin quis varius vitae, rhoncus laoreet neque. Mauris euismod fermentum urna vulputate tincidunt.
Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed nec eros ac orci mollis pulvinar. Nam ornare efficitur turpis vel porta. Maecenas venenatis ultricies dui id elementum. Vivamus eget imperdiet neque. Nunc dignissim elit at ante imperdiet maximus. Pellentesque sodales ultricies nisi, eu maximus nunc scelerisque non. Sed malesuada eu ex id pulvinar. Phasellus interdum eleifend porttitor.
Vestibulum nec faucibus nisl. Suspendisse pretium, nunc sit amet fringilla sollicitudin, nunc dui mattis ipsum, quis suscipit mauris augue a purus. Donec imperdiet scelerisque lectus a ultrices. Mauris ante leo, fermentum in orci et, ultricies laoreet erat. Donec sollicitudin ultricies nunc at scelerisque. Nulla et arcu nec lacus sagittis ornare. Nulla facilisi.
In efficitur augue non consequat consectetur. Etiam tempus est eu mi efficitur, id fermentum augue iaculis. Mauris luctus cursus diam vitae mollis. Aliquam erat volutpat. Donec est sapien, dapibus sed interdum interdum, dignissim nec risus. Morbi tincidunt justo sit amet metus facilisis porttitor. Maecenas luctus lacus at metus feugiat scelerisque. Aenean sed diam condimentum, ornare nunc non, tempus metus. Nam semper sed ante vitae auctor. Vestibulum id hendrerit felis. Suspendisse porta ex eget dapibus pellentesque. Curabitur nec odio et lorem tincidunt porta. Pellentesque lacinia libero id lectus volutpat lobortis. Nulla facilisi. " },
                new Product { Id = 2, Name = "Test product 2", Price = 4.99m, Summary = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec sem condimentum odio auctor tristique vestibulum in lacus. Praesent eu ultricies lectus. Integer justo dui, luctus nec porttitor ac, lobortis quis sem. Aliquam erat volutpat. Sed vitae semper enim. Vivamus ut leo quis tortor scelerisque ultricies. Proin aliquet, arcu sit amet rhoncus rhoncus, nisl felis rhoncus sapien, sit amet iaculis velit quam sit amet nisi. ", Description = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec sem condimentum odio auctor tristique vestibulum in lacus. Praesent eu ultricies lectus. Integer justo dui, luctus nec porttitor ac, lobortis quis sem. Aliquam erat volutpat. Sed vitae semper enim. Vivamus ut leo quis tortor scelerisque ultricies. Proin aliquet, arcu sit amet rhoncus rhoncus, nisl felis rhoncus sapien, sit amet iaculis velit quam sit amet nisi.
Aliquam cursus viverra erat, at luctus quam ornare eu. Vestibulum a pretium mi. Sed ultrices, mi in eleifend aliquet, velit tellus feugiat libero, eu tincidunt diam sapien ac sapien. In rutrum lacus quis mi cursus, non sollicitudin ligula porttitor. Curabitur sem leo, laoreet at sollicitudin eu, dapibus eu enim. Nullam libero mi, sollicitudin quis varius vitae, rhoncus laoreet neque. Mauris euismod fermentum urna vulputate tincidunt.
Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed nec eros ac orci mollis pulvinar. Nam ornare efficitur turpis vel porta. Maecenas venenatis ultricies dui id elementum. Vivamus eget imperdiet neque. Nunc dignissim elit at ante imperdiet maximus. Pellentesque sodales ultricies nisi, eu maximus nunc scelerisque non. Sed malesuada eu ex id pulvinar. Phasellus interdum eleifend porttitor.
Vestibulum nec faucibus nisl. Suspendisse pretium, nunc sit amet fringilla sollicitudin, nunc dui mattis ipsum, quis suscipit mauris augue a purus. Donec imperdiet scelerisque lectus a ultrices. Mauris ante leo, fermentum in orci et, ultricies laoreet erat. Donec sollicitudin ultricies nunc at scelerisque. Nulla et arcu nec lacus sagittis ornare. Nulla facilisi.
In efficitur augue non consequat consectetur. Etiam tempus est eu mi efficitur, id fermentum augue iaculis. Mauris luctus cursus diam vitae mollis. Aliquam erat volutpat. Donec est sapien, dapibus sed interdum interdum, dignissim nec risus. Morbi tincidunt justo sit amet metus facilisis porttitor. Maecenas luctus lacus at metus feugiat scelerisque. Aenean sed diam condimentum, ornare nunc non, tempus metus. Nam semper sed ante vitae auctor. Vestibulum id hendrerit felis. Suspendisse porta ex eget dapibus pellentesque. Curabitur nec odio et lorem tincidunt porta. Pellentesque lacinia libero id lectus volutpat lobortis. Nulla facilisi. " },
                new Product { Id = 3, Name = "Test product 3", Price = 4.99m, Summary = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec sem condimentum odio auctor tristique vestibulum in lacus. Praesent eu ultricies lectus. Integer justo dui, luctus nec porttitor ac, lobortis quis sem. Aliquam erat volutpat. Sed vitae semper enim. Vivamus ut leo quis tortor scelerisque ultricies. Proin aliquet, arcu sit amet rhoncus rhoncus, nisl felis rhoncus sapien, sit amet iaculis velit quam sit amet nisi. ", Description = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec sem condimentum odio auctor tristique vestibulum in lacus. Praesent eu ultricies lectus. Integer justo dui, luctus nec porttitor ac, lobortis quis sem. Aliquam erat volutpat. Sed vitae semper enim. Vivamus ut leo quis tortor scelerisque ultricies. Proin aliquet, arcu sit amet rhoncus rhoncus, nisl felis rhoncus sapien, sit amet iaculis velit quam sit amet nisi.
Aliquam cursus viverra erat, at luctus quam ornare eu. Vestibulum a pretium mi. Sed ultrices, mi in eleifend aliquet, velit tellus feugiat libero, eu tincidunt diam sapien ac sapien. In rutrum lacus quis mi cursus, non sollicitudin ligula porttitor. Curabitur sem leo, laoreet at sollicitudin eu, dapibus eu enim. Nullam libero mi, sollicitudin quis varius vitae, rhoncus laoreet neque. Mauris euismod fermentum urna vulputate tincidunt.
Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed nec eros ac orci mollis pulvinar. Nam ornare efficitur turpis vel porta. Maecenas venenatis ultricies dui id elementum. Vivamus eget imperdiet neque. Nunc dignissim elit at ante imperdiet maximus. Pellentesque sodales ultricies nisi, eu maximus nunc scelerisque non. Sed malesuada eu ex id pulvinar. Phasellus interdum eleifend porttitor.
Vestibulum nec faucibus nisl. Suspendisse pretium, nunc sit amet fringilla sollicitudin, nunc dui mattis ipsum, quis suscipit mauris augue a purus. Donec imperdiet scelerisque lectus a ultrices. Mauris ante leo, fermentum in orci et, ultricies laoreet erat. Donec sollicitudin ultricies nunc at scelerisque. Nulla et arcu nec lacus sagittis ornare. Nulla facilisi.
In efficitur augue non consequat consectetur. Etiam tempus est eu mi efficitur, id fermentum augue iaculis. Mauris luctus cursus diam vitae mollis. Aliquam erat volutpat. Donec est sapien, dapibus sed interdum interdum, dignissim nec risus. Morbi tincidunt justo sit amet metus facilisis porttitor. Maecenas luctus lacus at metus feugiat scelerisque. Aenean sed diam condimentum, ornare nunc non, tempus metus. Nam semper sed ante vitae auctor. Vestibulum id hendrerit felis. Suspendisse porta ex eget dapibus pellentesque. Curabitur nec odio et lorem tincidunt porta. Pellentesque lacinia libero id lectus volutpat lobortis. Nulla facilisi. " },
                new Product { Id = 4, Name = "Test product 4", Price = 4.99m, Summary = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec sem condimentum odio auctor tristique vestibulum in lacus. Praesent eu ultricies lectus. Integer justo dui, luctus nec porttitor ac, lobortis quis sem. Aliquam erat volutpat. Sed vitae semper enim. Vivamus ut leo quis tortor scelerisque ultricies. Proin aliquet, arcu sit amet rhoncus rhoncus, nisl felis rhoncus sapien, sit amet iaculis velit quam sit amet nisi. ", Description = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec sem condimentum odio auctor tristique vestibulum in lacus. Praesent eu ultricies lectus. Integer justo dui, luctus nec porttitor ac, lobortis quis sem. Aliquam erat volutpat. Sed vitae semper enim. Vivamus ut leo quis tortor scelerisque ultricies. Proin aliquet, arcu sit amet rhoncus rhoncus, nisl felis rhoncus sapien, sit amet iaculis velit quam sit amet nisi.
Aliquam cursus viverra erat, at luctus quam ornare eu. Vestibulum a pretium mi. Sed ultrices, mi in eleifend aliquet, velit tellus feugiat libero, eu tincidunt diam sapien ac sapien. In rutrum lacus quis mi cursus, non sollicitudin ligula porttitor. Curabitur sem leo, laoreet at sollicitudin eu, dapibus eu enim. Nullam libero mi, sollicitudin quis varius vitae, rhoncus laoreet neque. Mauris euismod fermentum urna vulputate tincidunt.
Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed nec eros ac orci mollis pulvinar. Nam ornare efficitur turpis vel porta. Maecenas venenatis ultricies dui id elementum. Vivamus eget imperdiet neque. Nunc dignissim elit at ante imperdiet maximus. Pellentesque sodales ultricies nisi, eu maximus nunc scelerisque non. Sed malesuada eu ex id pulvinar. Phasellus interdum eleifend porttitor.
Vestibulum nec faucibus nisl. Suspendisse pretium, nunc sit amet fringilla sollicitudin, nunc dui mattis ipsum, quis suscipit mauris augue a purus. Donec imperdiet scelerisque lectus a ultrices. Mauris ante leo, fermentum in orci et, ultricies laoreet erat. Donec sollicitudin ultricies nunc at scelerisque. Nulla et arcu nec lacus sagittis ornare. Nulla facilisi.
In efficitur augue non consequat consectetur. Etiam tempus est eu mi efficitur, id fermentum augue iaculis. Mauris luctus cursus diam vitae mollis. Aliquam erat volutpat. Donec est sapien, dapibus sed interdum interdum, dignissim nec risus. Morbi tincidunt justo sit amet metus facilisis porttitor. Maecenas luctus lacus at metus feugiat scelerisque. Aenean sed diam condimentum, ornare nunc non, tempus metus. Nam semper sed ante vitae auctor. Vestibulum id hendrerit felis. Suspendisse porta ex eget dapibus pellentesque. Curabitur nec odio et lorem tincidunt porta. Pellentesque lacinia libero id lectus volutpat lobortis. Nulla facilisi. " }
        };

        public async Task<Product> GetProductById(int id)
        {
            return products.FirstOrDefault(p => p.Id == id);
        }
    }
}
